name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.8.1
      - run: npm ci
      - run: npm run dev
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}